drop table Client if exists
drop table SalesOrder if exists
drop table OrderItem if exists


/*Tables*/
create table Client(clientCode char(60) not null, name varchar(255) not null, street varchar(255) not null, zip int not null, city varchar(255) not null, countryCode char(3) not null, primary key (clientCode))
create table SalesOrder(orderCode char(60) not null, forCustomerCode char(60) not null, primary key (orderCode))
create table OrderItem (id bigint generated by default as identity (start with 1), lineId int not null, item varchar(255) not null, price double not null, primary key (id))

/*Data*/
