drop table Client if exists
drop table OrderLine if exists
drop table SalesOrder if exists

drop table Account if exists
drop table JournalEntry if exists
drop table Journal if exists



-- Tables
create table Client(clientCode varchar(60) not null, name varchar(255) not null, street varchar(255) not null, zip int not null, city varchar(255) not null, countryCode varchar(3) not null, primary key (clientCode))
create table SalesOrder(orderCode varchar(60) not null, forCustomerCode varchar(60) not null, state varchar(30) not null, primary key (orderCode))
create table OrderLine (id bigint generated by default as identity (start with 1), lineId int not null, item varchar(255) not null, price double not null, currencyCode varchar(3) not null, lines_orderCode varchar(60), primary key (id), foreign key (lines_orderCode) references SalesOrder(orderCode))

create table Account(id bigint generated by default as identity (start with 1), name varchar(60) not null, solde double not null, primary key(id))
create table Journal(id bigint generated by default as identity (start with 1), forAccountName varchar(60) not null, primary key(id))
create table JournalEntry(id bigint generated by default as identity (start with 1), journal_id bigint, somme double not null, solde double not null, operation varchar(20) not null, recordDate timestamp not null, primary key(id), foreign key (journal_id) references Journal(id))
-- Data
insert into Account (name, solde) values ('test-account-0', 0.0)
insert into Journal (forAccountName) values ('test-account-0', 0.0)