drop table Client if exists
drop table OrderLine if exists
drop table SalesOrder if exists



-- Tables
create table Client(clientCode varchar(60) not null, name varchar(255) not null, street varchar(255) not null, zip int not null, city varchar(255) not null, countryCode varchar(3) not null, primary key (clientCode))
create table SalesOrder(orderCode varchar(60) not null, forCustomerCode varchar(60) not null, state varchar(30) not null, primary key (orderCode))
create table OrderLine (id bigint generated by default as identity (start with 1), lineId int not null, item varchar(255) not null, price double not null, currencyCode varchar(3) not null, lines_orderCode varchar(60), primary key (id), foreign key (lines_orderCode) references SalesOrder(orderCode))

-- Data
